const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Levis Denim',
      category: 'Pant',
      image: '/images/p2.jpg',
      price: 4800,
      countInStock: 20,
      brand: 'levis',
      rating: 5,
      numReviews: 23,
      description: 'high stretch product',
    },
    {
      _id: '3',
      name: 'lee brill Pant',
      category: 'Pant',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 7,
      brand: 'lee cooper',
      rating: 2.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Raymond Formal Shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 3500,
      countInStock: 12,
      brand: 'Raymond',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Polo Round Shirt',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 700,
      countInStock: 2,
      brand: 'Polo',
      rating: 4.2,
      numReviews: 11,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Adidas Jogger Pant',
      category: 'pant',
      image: '/images/p6.jpg',
      price: 3900,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 5,
      description: 'high quality product',
    },
  ],
};

export default data;
